--- #YAML:1.0
name:                Tie-Judy
version:             0.05
abstract:            Perl extension for using a Judy array instead of a hash.
license:             ~
author:              
    - Ben Holzman <bah@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
